routes/web.php
<?php

use App\Models\Stack;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (!Auth::guest()) {
        return redirect()->route('dashbaord');
    }
    return view('welcome');
});

Auth::routes();

Route::group([
    'prefix' => '/user',
    'namespace' => 'User',
    'middleware' => 'auth'
], function () {
});

Route::group([
    'prefix' => '',
    'namespace' => 'Member',
    'middleware' => 'auth'
], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group([
        'prefix' => '/cards',
        'as' => 'cards.'
    ], function () {
        Route::post('/', 'CardController@store')->name('store');
        Route::get('/create', 'CardController@create')->name('create');
    });

    Route::group([
        'prefix' => '/stacks',
        'as' => 'stacks.'
    ], function () {
        Route::post('', 'StackController@store')->name('store');
        Route::get('/{id}/details', 'Stackcontroller@show')->name('show');
    });
});

Route::group([
    'prefix' => '/admin',
    'namespace' => 'Admin',
    'middleware' => 'admin'
], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashbaord');
});

app/Models/Card.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Card extends Model
{
    use SoftDeletes;

    protected $attributes = [
        'total_read' => 0,
        'is_public' => false
    ];

    public function stacks()
    {
        return $this->belongsToMany('App\Models\Stack');
    }
}

app/Http/Controllers/Member/CardController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use App\Models\Card;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;

class CardController extends Controller
{

    public function create()
    {
        return view('member.cards.create.index');
    }

    public function store(Request $request)
    {
        $front_card_path = $request->file('front_card')->store('images');
        $back_card_path = $request->file('back_card')->store('images');

        $user_id = Auth::user()->id;

        $card = new Card();
        $card->created_by = $user_id;
        $card->card_front = $front_card_path;
        $card->card_back = $back_card_path;
        $card->save();

        $card->stacks()->attach($request->stacks);

        return Redirect('/');
    }

    public function update(Request $request)
    {

    }

    public function delete($id)
    {
    }

    public function forceDelete($id)
    {
    }
}

app/View/Components/Shared/Card.php
<?php

namespace App\View\Components\Shared;

use Illuminate\View\Component;

class Card extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.shared.card');
    }
}

resources/views/member/cards/create/index.blade.php
<x-layouts.member-app page-key="CREATE_CARDS">
    <h1 class="mb-4">Create Card</h1>
    <form method="POST" action="{{ route('cards.store') }}" enctype="multipart/form-data">
        @csrf
        <h3>Stacks</h3>
        <div class="d-flex flex-wrap mb-4" id="stackList">
            <x-shared.tag-add />
        </div>
        <div id="stackListInput"></div>
        <div class="mb-4 mr-sm-4 card-preview-wrapper">
            <h3>Front</h3>
            <div class="card-preview">
                <img class="w-100 h-100" id="previewFrontCard">
            </div>
            <div class="custom-file">
                <input name="front_card" type="file" class="custom-file-input" id="inputFrontCard">
                <label class="custom-file-label text-truncate" for="inputFrontCard">Choose file</label>
            </div>
        </div>
        <div class="mb-4 card-preview-wrapper">
            <h3>Back</h3>
            <div class="card-preview">
                <img class="w-100 h-100" id="previewBackCard">
            </div>
            <div class="custom-file">
                <input name="back_card" type="file" class="custom-file-input" id="inputBackCard">
                <label class="custom-file-label text-truncate" for="inputBackCard">Choose file</label>
            </div>
        </div>
        <div class="d-flex">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary ml-2">Create</button>
        </div>
    </form>

    @push('scripts')
    <script>
        $(document).ready(function () {

            $('#inputFrontCard').change(function () {
                if (this.files && this.files[0]) {
                    let reader =  new FileReader();

                    reader.onload = function(e) {
                        $('#previewFrontCard').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(this.files[0]);

                    $(this).next('.custom-file-label').html($(this).val());

                }
            })

            $('#inputBackCard').change(function () {
                if (this.files && this.files[0]) {
                    let reader =  new FileReader();

                    reader.onload = function(e) {
                        $('#previewBackCard').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(this.files[0]);

                    $(this).next('.custom-file-label').html($(this).val());

                }
            })

        })



    </script>
    @endpush

</x-layouts.member-app>